language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
env:
  global:
  - secure: Zm3+w0VQRPg/MYL5driKpXz8w41q8bugXO1sVxq2l5ct0cbRW219Gbn1PVCe/R+RQK9imj0MO3Bnp2aNgwEjx6N/sHWUk8Q+CZDc8fJR3LMA+/cfw33QpoJuepxeWcSvpPoQFKII1k241XKCtKPcH3oFDz4ty3V3dXlTRSp6yO3dhHbEoQXPIBvjtYFkbl8LszuBOkoEhd1BlWwSBvlS4EX7kZIRToepplzNVgybqMVv1DaUV1Dimx+nzORqGq40+rFFf9GEbUqHuN3aDnvb83WQzQiyw2/i1bKG9vOcM6niyP2Vg4ypX3jDLLPdKwTHvaJusUX9HaUVjPPsRgdb9E2eec7UaJ76N0zdcvKSuLe78tmn+u1XlFoeAGET5BfyjcetmednQYbSE85Y+Ft0CkpYAw9L0KjgFJlrN9aTJ8Kl689xCYk+GSNfHVG7J3du47MZQAQZ06rjoOLihrO130d3A59gFsXY5L/wWRrhTDl2pqkKGfJxQSNaoLeO1Rmcz19V+IEvoxoxEaIPhF5tMKFyR9db4o+qR1znrb8jT+2Mn/x47rOtw7ZBYdaPmXC1Z11IyO2RRZAXPwVh2LLRp9WAMkhkqL/PNF/Juu5rptz0LBTAH3o1wTlfP3uNfigtOgxAQlfArVL6wI+YrvFcXUBUnq5XOzBbiTLI9LDZplk=
  - secure: vjEGRy1dhD+qJGpIPUKqfExUrbwbl/bPZQruezeuzH53JLKK0FG5wZ1DRufBGzNd1JUSvCKuNHctNqWUFM+NYkfcoJIUnIzFm3wpx9rixgHJwPw14eS99SxcvXS3eo/k8/a+/lHYR2I+zMChk/rr4G9ygHCCLe5gupktjEfdEZ1tPMT283b05PTNvEwygKT6bbCDmmMfKNflWL5qhnErcBe5O6Xq6nHyVzqAwCUg1t1a3/rs6ItlL4z7Z4AEGdnTXpMKJZrEaloStxaKXQD/EfbQWjFlpcUU4b4tnwTA+urIS+ed9pEjg365M6Oj9QtfSafXmtwShMoBgxdBYkBK/Vucq2Rwy9Wktn631EskOsV9D3SsmR4AVrCQVUHMtrVe0grRzkScd1MEo2PBfQLLGuJZ99GRLsSD8LWHPcatwmrln0bgy6v8iNBAyX41twjiJE8i1ZaTxMYsiKwgKlWXqd7CQXAWMpTmFx7wk107wJ4AJ/++3g5U9ltd27Ul3Z7NUHGJ6N6iLUqAdjRXyB/ZtujNZu1HSPwuHVAqXH74FK6KYVNlyI0jfSEui2vAMMitnp+JndItcIqM+QwyG0XBy5ySDw/+XvFMMwWQsVZQxCiKcY0gheeBs7aBN0jMs4eq+SGGnqtYgWYRBj4eJTAvVG2CTVvKXqm4rxTQ+VaOuLw=
  - secure: ZUeyUsYvfp+OQZArzdUHN8Z5DTOJQNJNezYaHC5f97G2ooNAmJLSc+f/Ed0YLHv0UOY5U8GE2Z2c1tK28TlYvKdNG97DtPF/aanHeNPKHUtpBC8EXV9nZntkr9EiO9/u27hK4sTBfnxg80Omov6A0SPdS9PoEJ8+eAcm1LKf3mjUKZn+IbzHl5wm14dqu87XmlvaqB4t5vbUEDvbg2FZM14nBh62WX8l+X+jQEb43lfYs2FNEGonEBZehCdUIdeBP51v9rOoUk1dfpLNDmofIipGN/v3LHi5GXnSQyje3PcIZ1QLkMrCLFVnQsQN+qHag5zbIIK0qnnuW62iSLweh7qe/vqBMD4/80sKIxAmb0yfQLbG/hzLmTAUOPlgcs/zfKjXcJo2wxBhxmi4ZYSQXJCD1Aegv30oGudmNrk6XkoBkK2n+f3GZ9kzZto2chRPBtD32xUNKC/9IzxCnNvOVhT2giwJIAtsR7JhXSV2GBwqZ50n2JzZNDlA647RU4WV3RLkTjss214G1pzaS/NTh/V+dQMvEg9W56B9OuczLdVGCNWU8U31ak1bMF+db5+tOwIBKtiKvnfomQt2fX9uruLRYEk3Z6c35UNHB5u8cCdyGRmND+RxUaPkRFwyBxhCNAggQejzNAnSbgKMuja+aEcAm9uhT2X4gr9ho2fXKos=
sudo: required
services:
- docker
after_success:
- echo $DOCKER_USERNAME
- image=liping511/mtaas:$(date +"%Y%m%d%H%M%S")
- docker build -t $image --build-arg MYSQL_DB_HOST=$MYSQL_DB_HOST --build-arg MYSQL_DB_PORT=$MYSQL_DB_PORT
  --build-arg MYSQL_DB_USERNAME=$MYSQL_DB_USERNAME --build-arg MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD
  --build-arg MYSQL_DB_DATABASE=$MYSQL_DB_DATABASE --build-arg MONGODB_URI=$MONGODB_URI .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $image
